server:
  port: 8082
spring:
  application:
    name:
      course-service
  data:
    elasticsearch:
      client:
        elasticsearch:
          uris: http://localhost:9200
      repositories:
        enabled: true
  servlet:
    multipart:
        location: /uploads
        max-file-size: 500MB
        max-request-size: 500MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


