server:
  port: 8082
spring:
  application:
    name:
      course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/coursedb
    username: root
    password: AliSami14
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


