server:
  port: 8081
spring:
  application:
     name:
        user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-data-base
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SENDER_MAIL}
    password: ${EMAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  jpa:
    hibernate:
      ddl-auto: create-only
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
    com.example.userService: DEBUG

jwt:
  secret:
    ${JWT_SECRET_KEY}
  access:
    expire:
      ${JWT_ACCESS_EXPIRATION}
  refresh:
    expire:
      ${JWT_REFRESH_EXPIRATION}

cache:
  type: redis

