server:
  port: 8081
spring:
  application:
     name:
        user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-data-base
    username: root
    password: ghandy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
    com.example.userService: DEBUG