server:
  port: 8085

spring:
  application:
    name: chat-service

  # MongoDB Configuration (Atlas)

  data:
    mongodb:
      uri: ${DB_URI}


    # Redis Configuration
    redis:
      host: localhost
      port: 6379
      timeout: 60000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1



# WebSocket Configuration
websocket:
  endpoint: /ws
  allowed-origins: "*"
